In [4]:
import requests
import lxml.html
from bs4 import BeautifulSoup
import re
import pandas as pd

# Experimented with getting any bullets after a 'bold' tag of "Qualifications".... It worked!

In [5]:
URL='https://www.indeed.com/viewjob?jk=11baba484db23433&from=serp&vjs=3'
r=requests.get(URL)
page=r.text
soup=BeautifulSoup(page,'lxml')

In [6]:
Qualifications_tag = soup.find('b', text=re.compile('Qualifications'))
try:
    ul_tag = Qualifications_tag.find_next('ul')
except AttributeError: 
    print("None Found")
else:
    for li_tag in ul_tag:
        print(li_tag.string)

Currently has or is in the process of obtaining their BA/BS or Masters in Computer Science, Mathematics, Economics, Statistics, Applied Sciences like Biostatistics, Physics, Chemistry, Computational Neurology

Some Engineering experience and or project course work using large data systems on SQL, Hadoop, etc.

Proficiency using one or more programming or scripting language to work with data such as: Python, Perl, or C#.

Some experience and or project course work performing data analysis and applying statistics working with tools such as: Excel, R, MATLAB, AMPL, or SAS.

Some experience and or project course work with product and service telemetry systems.

Some A/B Testing or experimentation (this can be from conducting real life science experiments, hypothesis testing in stats etc.) Not required but ideal.

Some experience or course work applying basic ML to a type of data and or used algorithms to conduct experiments on data. Machine Learning strongly encouraged.

Passion to learn from your peers, manager, and other stakeholders in the Data Science domain.

Ability to interact with peers and stakeholders to drive product and business impact.

Strong interpersonal and communications skills.

# Now to put it in a loop!
# First part of the code is just getting the website links to loop through.

In [7]:
#Doing this with up to 20 first until I know it works....

url_template="http://www.indeed.com/jobs?q=data_scientist&1=USA&start={}"
max_results=20
Linkdf=[]

for start in range(0, max_results, 10):
    url=url_template.format(start)
    html=requests.get(url)
    soup=BeautifulSoup(html.content,'html.parser', from_encoding="utf-8")
    
    #for each in soup.find_all(a_="href"):
    page_links=soup.find_all('a',{'href':re.compile("/rc/")})
    for items in page_links:
        Linkdf.append(items['href'])
        print(Linkdf) #Sanity Check

['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', '/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', '/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3', '/rc/clk?jk=6e3926655e10a965&fccid=a12996b2625d253a&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', '/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3', '/rc/clk?jk=6e3926655e10a965&fccid=a12996b2625d253a&vjs=3', '/rc/clk?jk=1e686166d30fd118&fccid=de71a49b535e21cb&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', '/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3', '/rc/clk?jk=6e3926655e10a965&fccid=a12996b2625d253a&vjs=3', '/rc/clk?jk=1e686166d30fd118&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=2a6b19462f0f4308&fccid=9bdf8e3a2f3d19e4&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', '/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3', '/rc/clk?jk=6e3926655e10a965&fccid=a12996b2625d253a&vjs=3', '/rc/clk?jk=1e686166d30fd118&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=2a6b19462f0f4308&fccid=9bdf8e3a2f3d19e4&vjs=3', '/rc/clk?jk=a23cedc7cf86d5f0&fccid=4441a1e77a201111&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', '/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3', '/rc/clk?jk=6e3926655e10a965&fccid=a12996b2625d253a&vjs=3', '/rc/clk?jk=1e686166d30fd118&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=2a6b19462f0f4308&fccid=9bdf8e3a2f3d19e4&vjs=3', '/rc/clk?jk=a23cedc7cf86d5f0&fccid=4441a1e77a201111&vjs=3', '/rc/clk?jk=1942a17d2bd166e1&fccid=ae0c894528aa6eee&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', '/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3', '/rc/clk?jk=6e3926655e10a965&fccid=a12996b2625d253a&vjs=3', '/rc/clk?jk=1e686166d30fd118&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=2a6b19462f0f4308&fccid=9bdf8e3a2f3d19e4&vjs=3', '/rc/clk?jk=a23cedc7cf86d5f0&fccid=4441a1e77a201111&vjs=3', '/rc/clk?jk=1942a17d2bd166e1&fccid=ae0c894528aa6eee&vjs=3', '/rc/clk?jk=f7a1c4b21d7446a3&fccid=bf49b2e47bbdeffa&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', '/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3', '/rc/clk?jk=6e3926655e10a965&fccid=a12996b2625d253a&vjs=3', '/rc/clk?jk=1e686166d30fd118&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=2a6b19462f0f4308&fccid=9bdf8e3a2f3d19e4&vjs=3', '/rc/clk?jk=a23cedc7cf86d5f0&fccid=4441a1e77a201111&vjs=3', '/rc/clk?jk=1942a17d2bd166e1&fccid=ae0c894528aa6eee&vjs=3', '/rc/clk?jk=f7a1c4b21d7446a3&fccid=bf49b2e47bbdeffa&vjs=3', '/rc/clk?jk=020c5d3fcc757260&fccid=79462bd4e96de970&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', '/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3', '/rc/clk?jk=6e3926655e10a965&fccid=a12996b2625d253a&vjs=3', '/rc/clk?jk=1e686166d30fd118&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=2a6b19462f0f4308&fccid=9bdf8e3a2f3d19e4&vjs=3', '/rc/clk?jk=a23cedc7cf86d5f0&fccid=4441a1e77a201111&vjs=3', '/rc/clk?jk=1942a17d2bd166e1&fccid=ae0c894528aa6eee&vjs=3', '/rc/clk?jk=f7a1c4b21d7446a3&fccid=bf49b2e47bbdeffa&vjs=3', '/rc/clk?jk=020c5d3fcc757260&fccid=79462bd4e96de970&vjs=3', '/rc/clk?jk=fc0ab00fa6030861&fccid=6e1b86edb37e1c98&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', '/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3', '/rc/clk?jk=6e3926655e10a965&fccid=a12996b2625d253a&vjs=3', '/rc/clk?jk=1e686166d30fd118&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=2a6b19462f0f4308&fccid=9bdf8e3a2f3d19e4&vjs=3', '/rc/clk?jk=a23cedc7cf86d5f0&fccid=4441a1e77a201111&vjs=3', '/rc/clk?jk=1942a17d2bd166e1&fccid=ae0c894528aa6eee&vjs=3', '/rc/clk?jk=f7a1c4b21d7446a3&fccid=bf49b2e47bbdeffa&vjs=3', '/rc/clk?jk=020c5d3fcc757260&fccid=79462bd4e96de970&vjs=3', '/rc/clk?jk=fc0ab00fa6030861&fccid=6e1b86edb37e1c98&vjs=3', '/rc/clk?jk=7bc714e40a6c3421&fccid=e5719b46cb3432f4&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', '/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3', '/rc/clk?jk=6e3926655e10a965&fccid=a12996b2625d253a&vjs=3', '/rc/clk?jk=1e686166d30fd118&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=2a6b19462f0f4308&fccid=9bdf8e3a2f3d19e4&vjs=3', '/rc/clk?jk=a23cedc7cf86d5f0&fccid=4441a1e77a201111&vjs=3', '/rc/clk?jk=1942a17d2bd166e1&fccid=ae0c894528aa6eee&vjs=3', '/rc/clk?jk=f7a1c4b21d7446a3&fccid=bf49b2e47bbdeffa&vjs=3', '/rc/clk?jk=020c5d3fcc757260&fccid=79462bd4e96de970&vjs=3', '/rc/clk?jk=fc0ab00fa6030861&fccid=6e1b86edb37e1c98&vjs=3', '/rc/clk?jk=7bc714e40a6c3421&fccid=e5719b46cb3432f4&vjs=3', '/rc/clk?jk=1e58d06b2439173c&fccid=5434780ac3971e0d&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', '/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3', '/rc/clk?jk=6e3926655e10a965&fccid=a12996b2625d253a&vjs=3', '/rc/clk?jk=1e686166d30fd118&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=2a6b19462f0f4308&fccid=9bdf8e3a2f3d19e4&vjs=3', '/rc/clk?jk=a23cedc7cf86d5f0&fccid=4441a1e77a201111&vjs=3', '/rc/clk?jk=1942a17d2bd166e1&fccid=ae0c894528aa6eee&vjs=3', '/rc/clk?jk=f7a1c4b21d7446a3&fccid=bf49b2e47bbdeffa&vjs=3', '/rc/clk?jk=020c5d3fcc757260&fccid=79462bd4e96de970&vjs=3', '/rc/clk?jk=fc0ab00fa6030861&fccid=6e1b86edb37e1c98&vjs=3', '/rc/clk?jk=7bc714e40a6c3421&fccid=e5719b46cb3432f4&vjs=3', '/rc/clk?jk=1e58d06b2439173c&fccid=5434780ac3971e0d&vjs=3', '/rc/clk?jk=353ef6d89a4518c8&fccid=fab75f149007c659&vjs=3']
['/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', '/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', '/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', '/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3', '/rc/clk?jk=6e3926655e10a965&fccid=a12996b2625d253a&vjs=3', '/rc/clk?jk=1e686166d30fd118&fccid=de71a49b535e21cb&vjs=3', '/rc/clk?jk=2a6b19462f0f4308&fccid=9bdf8e3a2f3d19e4&vjs=3', '/rc/clk?jk=a23cedc7cf86d5f0&fccid=4441a1e77a201111&vjs=3', '/rc/clk?jk=1942a17d2bd166e1&fccid=ae0c894528aa6eee&vjs=3', '/rc/clk?jk=f7a1c4b21d7446a3&fccid=bf49b2e47bbdeffa&vjs=3', '/rc/clk?jk=020c5d3fcc757260&fccid=79462bd4e96de970&vjs=3', '/rc/clk?jk=fc0ab00fa6030861&fccid=6e1b86edb37e1c98&vjs=3', '/rc/clk?jk=7bc714e40a6c3421&fccid=e5719b46cb3432f4&vjs=3', '/rc/clk?jk=1e58d06b2439173c&fccid=5434780ac3971e0d&vjs=3', '/rc/clk?jk=353ef6d89a4518c8&fccid=fab75f149007c659&vjs=3', '/rc/clk?jk=425a80f872055c17&fccid=e20c9dc5e88f0a63&vjs=3']

In [8]:
len(Linkdf)

18

In [9]:
#Create array with just last one (use the code above to use the right length)
Finallinks=Linkdf[:18]

#This code allows the code to display the full website instead of truncating
pd.set_option('display.max_colwidth',-1)

#Moving it to a data frame
data = {'links':Finallinks}
df = pd.DataFrame(data, columns=['links'])

#append indeed.com to the front of each
df['Web'] = 'https://www.indeed.com'
df['URL'] = df.Web.str.cat(df.links)

In [11]:
#pull out just a list of the websites.
websites=list(df['URL'])
#websites.append(index)
print(websites) #Sanity Check

['https://www.indeed.com/rc/clk?jk=267e7cf7de2959c7&fccid=de71a49b535e21cb&vjs=3', 'https://www.indeed.com/rc/clk?jk=7daefd0b4302961e&fccid=734cb5a01ee60f80&vjs=3', 'https://www.indeed.com/rc/clk?jk=11baba484db23433&fccid=734cb5a01ee60f80&vjs=3', 'https://www.indeed.com/rc/clk?jk=b34757e702ad2ee0&fccid=245cecf5f0560d8c&vjs=3', 'https://www.indeed.com/rc/clk?jk=7f6b28670bfcbd0e&fccid=913e1b259c8d65e2&vjs=3', 'https://www.indeed.com/rc/clk?jk=8c9277695be5f139&fccid=b2d899f595c435be&vjs=3', 'https://www.indeed.com/rc/clk?jk=6e3926655e10a965&fccid=a12996b2625d253a&vjs=3', 'https://www.indeed.com/rc/clk?jk=1e686166d30fd118&fccid=de71a49b535e21cb&vjs=3', 'https://www.indeed.com/rc/clk?jk=2a6b19462f0f4308&fccid=9bdf8e3a2f3d19e4&vjs=3', 'https://www.indeed.com/rc/clk?jk=a23cedc7cf86d5f0&fccid=4441a1e77a201111&vjs=3', 'https://www.indeed.com/rc/clk?jk=1942a17d2bd166e1&fccid=ae0c894528aa6eee&vjs=3', 'https://www.indeed.com/rc/clk?jk=f7a1c4b21d7446a3&fccid=bf49b2e47bbdeffa&vjs=3', 'https://www.indeed.com/rc/clk?jk=020c5d3fcc757260&fccid=79462bd4e96de970&vjs=3', 'https://www.indeed.com/rc/clk?jk=fc0ab00fa6030861&fccid=6e1b86edb37e1c98&vjs=3', 'https://www.indeed.com/rc/clk?jk=7bc714e40a6c3421&fccid=e5719b46cb3432f4&vjs=3', 'https://www.indeed.com/rc/clk?jk=1e58d06b2439173c&fccid=5434780ac3971e0d&vjs=3', 'https://www.indeed.com/rc/clk?jk=353ef6d89a4518c8&fccid=fab75f149007c659&vjs=3', 'https://www.indeed.com/rc/clk?jk=425a80f872055c17&fccid=e20c9dc5e88f0a63&vjs=3']

# This is where the loop for Qualifications starts

## Pay attention to the last 3 lines...the location of the code makes a difference, but none are correct (yet)

## This loop prints only the last bulleted item

In [8]:
Qualifications=[]

for url in websites:
    r=requests.get(url)
    page=r.text
    soup=BeautifulSoup(page,'lxml')
    
    Qualifications_tag = soup.find('b', text=re.compile('Qualifications'))
    try:
        ul_tag = Qualifications_tag.find_next('ul')
    except AttributeError: 
        Qualification="None Found"
    else:
        for li_tag in ul_tag:
            Qualification=li_tag.string
    
    Qualifications.append(Qualification)
        #Qualifications.append(Qualification)
            #Qualifications.append(Qualification)

In [9]:
df_qualifications=pd.DataFrame({'Qualifications': Qualifications})
df_qualifications

                                                                                                                   Qualifications
0   None Found
1   None Found
2   \nExperience building scalable data models and performing complex relational database queries using SQL (Oracle, MySQL), etc.
3   \nProfiling, cross-platform adaptively, are preferred
4   None Found
5   None Found
6   Proficient in queries, report writing and presenting findings
7   \nStrong interpersonal and communications skills.
8   Visualize and communicate findings and provide a quantitative framework for evaluating and analyzing alternatives
9   \n
10  None Found
11  None Found
12  None Found

## This loop prints only the last bulleted item and no 'None Found'.

In [10]:
Qualifications=[]

for url in websites:
    r=requests.get(url)
    page=r.text
    soup=BeautifulSoup(page,'lxml')
    
    Qualifications_tag = soup.find('b', text=re.compile('Qualifications'))
    try:
        ul_tag = Qualifications_tag.find_next('ul')
    except AttributeError: 
        Qualification="None Found"
    else:
        for li_tag in ul_tag:
            Qualification=li_tag.string
    
    #Qualifications.append(Qualification)
        Qualifications.append(Qualification)
            #Qualifications.append(Qualification)

In [11]:
df_qualifications=pd.DataFrame({'Qualifications': Qualifications})
df_qualifications

                                                    Qualifications
0  \nExperience with time series or signal processing analytics.
1  Help Center
2  \n
3  \nExperience working with data at scale in the Hadoop ecosystem
4  \nExperience with time series or signal processing analytics.

## This loop prints all of the bulleted items, but each on different lines and includes no 'none found'.

In [12]:
Qualifications=[]

for url in websites:
    r=requests.get(url)
    page=r.text
    soup=BeautifulSoup(page,'lxml')
    
    Qualifications_tag = soup.find('b', text=re.compile('Qualifications'))
    try:
        ul_tag = Qualifications_tag.find_next('ul')
    except AttributeError: 
        Qualification="None Found"
    else:
        for li_tag in ul_tag:
            Qualification=li_tag.string
    
    #Qualifications.append(Qualification)
        #Qualifications.append(Qualification)
            Qualifications.append(Qualification)

In [13]:
df_qualifications=pd.DataFrame({'Qualifications': Qualifications})
df_qualifications

                                                                                                                          Qualifications
0   \nBS Degree (Master’s preferred) Statistics, Machine Learning, Operations Research, Applied Math; or equivalent.
1   \n0 – 3 years of data science experience.
2   \nExperience with statistical and mathematical software
3   \nProven ability to develop system prototypes.
4   \nSQL skills
5   \nExcellent oral and written communication skills.
6   \nStrong documentation skills.
7   \nUnderstanding of machine learning techniques and the ability to invent.
8   \nBig data experience- Hadoop, Spark, Map-reduce, Hive, etc.
9   \nExperience with Agile methodology or similar lean startup approach to building software.
10  \nExperience with time series or signal processing analytics.
11  About
12  Help Center
13  \n
14  Intermediate knowledge of SQL
15  \n
16  A deep understanding of data concepts
17  \n
18  Eye For Business
19  \n
20  Interest in data visualization to tell a story
21  \n
22  Familiarity with Data Pipelines and ETL processes recommended practices
23  \n
24  You have a passion for this field and a good work ethic
25  \n
26  \nMaster’s degree or PhD in computer science, machine learning, data science, mathematics, statistics, or related quantitative field
27  \nThree years of experience in a data science or machine learning role
28  \nExcellent knowledge of major machine learning algorithms
29  \nFluent in Python and R
30  \nExperience with machine learning libraries and platforms, like Scikit-learn and Tensorflow
31  \nSolid statistical analysis skills and a good understanding of experimental design
32  \nExperience working with data at scale in the Hadoop ecosystem
33  \nBS Degree (Master’s preferred) Statistics, Machine Learning, Operations Research, Applied Math; or equivalent.
34  \n0 – 3 years of data science experience.
35  \nExperience with statistical and mathematical software
36  \nProven ability to develop system prototypes.
37  \nSQL skills
38  \nExcellent oral and written communication skills.
39  \nStrong documentation skills.
40  \nUnderstanding of machine learning techniques and the ability to invent.
41  \nBig data experience- Hadoop, Spark, Map-reduce, Hive, etc.
42  \nExperience with Agile methodology or similar lean startup approach to building software.
43  \nExperience with time series or signal processing analytics.

This loop has the most information but it's all on it's own line instead of by website.

In [23]:
Qualifications =[]
Qualification=[]

for url in websites:
    r=requests.get(url)
    page=r.text
    soup=BeautifulSoup(page,'lxml')
    
    Qualifications_tag = soup.find('b', text=re.compile('Qualifications'))
    try:
        ul_tag = Qualifications_tag.find_next('ul')
    except AttributeError: 
        Qualification="None Found"
        Qualifications.append(Qualification)
    else:
        for li_tag in ul_tag:
            Qualification=li_tag.string
            Qualifications.append(Qualification)
    Qualifications.append('end')

In [27]:
Qualifications =[]
Qualification=[]

for url in websites:
    r=requests.get(url)
    page=r.text
    soup=BeautifulSoup(page,'lxml')
    
    #while Qualifications_tag = soup.find('b', text=re.compile('Qualifications'))
    try:
        Qualfications_tag = soup.find('b',text=re.compile('Qualifications').find_next('ul'))
        #ul_tag = Qualifications_tag.find_next('ul')
    except AttributeError: 
        Qualification="None Found"
        Qualifications.append(Qualification)
    else:
        for li_tag in ul_tag:
            Qualification=li_tag.string
            Qualifications.append(Qualification)
    Qualifications.append('end')

In [28]:
df_qualifications=pd.DataFrame({'Qualifications': Qualifications})
df_qualifications

   Qualifications
0   None Found
1   end
2   None Found
3   end
4   None Found
5   end
6   None Found
7   end
8   None Found
9   end
10  None Found
11  end
12  None Found
13  end
14  None Found
15  end
16  None Found
17  end
18  None Found
19  end
20  None Found
21  end
22  None Found
23  end
24  None Found
25  end
26  None Found
27  end
28  None Found
29  end
30  None Found
31  end

In [17]:
Qualifications =[]
Qualification=[]
Skills=[]
Skill=[]
Responsibilities=[]
Responsibility=[]
Educations=[]
Education=[]
Requirements=[]
Requirement=[]

#Search_Values = ['Qualifications', 'Skills', 'Responsibilities', 'Education', 'Requirement']
i=0

for url in websites:
    r=requests.get(url)
    page=r.text
    soup=BeautifulSoup(page,'lxml')
    
    #for value in Search_values :
    #Qualifications_tag = soup.find('b', text=re.compile(value))
    Qualifications_tag = soup.find('b', text=re.compile('Qualifications'))
    try:
        ul_tag = Qualifications_tag.find_next('ul')
    except AttributeError: 
        Qualification="None Found"
        Qualifications.append({i,Qualification})
     

    else:
        for li_tag in ul_tag:
            Qualification=li_tag.string
            Qualifications.append({i,Qualification})
    i=i+1

In [18]:
Qualifications

[{0, 'None Found'},
 {1,
  'Experience in experiment design and applied machine learning predicting outcomes in large-scale, complex datasets.'},
 {1, 'Experience in R, Azure ML, Python, or other statistics/ML tools.'},
 {1,
  'Moderate coding skills. SQL or similar required. C# or other languages strongly preferred.'},
 {1,
  'Outstanding communication and collaboration skills. You can learn from and teach others.'},
 {1,
  'Strong drive for results. You have a proven record of shepherding experiments to create successful shipping products/services.'},
 {1,
  'Experience with prediction in adversarial (threat) environments highly desirable.'},
 {'\nCurrently has or is in the process of obtaining their BA/BS or Masters in Computer Science, Mathematics, Economics, Statistics, Applied Sciences like Biostatistics, Physics, Chemistry, Computational Neurology\n',
  2},
 {2,
  'Some Engineering experience and or project course work using large data systems on SQL, Hadoop, etc.'},
 {'\nProficiency using one or more programming or scripting language to work with data such as: Python, Perl, or C#.',
  2},
 {'\nSome experience and or project course work performing data analysis and applying statistics working with tools such as: Excel, R, MATLAB, AMPL, or SAS.',
  2},
 {'\nSome experience and or project course work with product and service telemetry systems.',
  2},
 {'\nSome A/B Testing or experimentation (this can be from conducting real life science experiments, hypothesis testing in stats etc.) Not required but ideal.',
  2},
 {'\nSome experience or course work applying basic ML to a type of data and or used algorithms to conduct experiments on data. Machine Learning strongly encouraged.',
  2},
 {'\nPassion to learn from your peers, manager, and other stakeholders in the Data Science domain.',
  2},
 {'\nAbility to interact with peers and stakeholders to drive product and business impact.',
  2},
 {'\nStrong interpersonal and communications skills.', 2},
 {3, 'None Found'},
 {4, 'None Found'},
 {5,
  'Must be eligible to obtain a Public Trust government security clearance.'},
 {'\n', 5},
 {5, 'Bachelor’s Degree.'},
 {'\n', 5},
 {5,
  'Coursework in statistics, analytics, decision science, or similar field.'},
 {'\n', 5},
 {5, 'Clear and concise verbal and written communication skills.'},
 {'\n', 5},
 {5,
  'Ability to research and confidently assemble an argument and then back it up with evidence.'},
 {'\n', 5},
 {5, None},
 {6, 'None Found'},
 {7, 'None Found'},
 {8,
  'Strong technical knowledge in the areas of computer science, big data architecture, data processing, and machine learning'},
 {9, 'None Found'},
 {10, 'Bachelor’s or Master’s degree in a quantitative field'},
 {'\nKnowledge of Python and/or R', 10},
 {'\nKnowledge of algorithms for data mining, machine learning, and/or natural language processing',
  10},
 {'\nPossess some understanding of statistical procedures used in advanced analytics',
  10},
 {'\nExperience processing large amounts of structured and unstructured data using Spark, Hive or other Big Data technologies',
  10},
 {'\nExperience building scalable data models and performing complex relational database queries using SQL (Oracle, MySQL), etc.',
  10},
 {11, 'About'},
 {11, 'Help Center'},
 {12, 'None Found'},
 {13, 'None Found'},
 {14, 'None Found'},
 {15, 'None Found'},
 {16, 'None Found'},
 {17, None},
 {17, None},
 {17, None},
 {17, None},
 {17, None},
 {17, None},
 {17, None}]